[package]
name = "makegen"
version = "0.1.0"
authors = ["Georgios Liontos <georgios.liontos@sgdigital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
